// <auto-generated />
using System;
using Gatherly.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gatherly.Api.Data.Migrations
{
    [DbContext(typeof(GatherlyContext))]
    partial class GatherlyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gatherly.Api.Entities.Study", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxMember")
                        .HasColumnType("integer");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserNameId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserNameId");

                    b.ToTable("Studies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = ".NET, Blazor, Razor",
                            CreatorId = 1,
                            Date = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Study .NET together!",
                            MaxMember = 4,
                            Place = "Dev Academy, New Market",
                            Title = "Let's study .NET"
                        });
                });

            modelBuilder.Entity("Gatherly.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileUrl")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hello! I'm Daisy",
                            Email = "daisy@daisy.com",
                            FullName = "DaisyChoi",
                            PasswordHash = "1234",
                            ProfileUrl = "",
                            UserName = "Daisy"
                        });
                });

            modelBuilder.Entity("Gatherly.Api.Entities.Study", b =>
                {
                    b.HasOne("Gatherly.Api.Entities.User", "UserName")
                        .WithMany("StudyPost")
                        .HasForeignKey("UserNameId");

                    b.Navigation("UserName");
                });

            modelBuilder.Entity("Gatherly.Api.Entities.User", b =>
                {
                    b.Navigation("StudyPost");
                });
#pragma warning restore 612, 618
        }
    }
}
